#!/bin/bash
START=$(date +%s)
`curl --form test_file=@/Users/eastagile/code/network_test/script/kats-yellow-flower.jpg http://networktest.herokuapp.com/test_upload`
END=$(date +%s)
result=$(( $END - $START))
curl --get -d period=$result -d id=$1 http://localhost:3001/upload_result

